# Name of the GitHub Action workflow
name: FOSSA License Compliance and Security Check

# Event triggers for the workflow
on:
  workflow_dispatch:  # Run this action manually from the GitHub Actions tab

# Define the jobs in the workflow
jobs:
  fossa-scan:
    # Specifies the type of runner to use
    runs-on: ubuntu-latest
    env:
      FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
    # Sequence of steps that make up a single job
    steps:
    # Checkout the code to the GitHub runner
    - name: Checkout Code
      uses: actions/checkout@v4

    # Run FOSSA Scan
    - name: Run FOSSA Scan
      uses: fossas/fossa-action@main

    # Run FOSSA Tests
    - name: Run FOSSA Tests
      uses: fossas/fossa-action@main
      run-tests: true  # Run FOSSA tests for policy checks

    - name: Generate FOSSA CSV Report
      if: always()
      run: fossa report attribution --format csv

#    - name: FTP Deploy
#      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
#      with:
#        server: ${{ secrets.WP_ENGINE_SERVER }}
#        username: ${{ secrets.WP_ENGINE_USERNAME }}
#        password: ${{ secrets.WP_ENGINE_PASSWORD }}
#        local-dir: './'
#        remote-dir: '/path/to/remote/directory/'
#        protocol: 'sftp'
#        port: 2222
