name: Create Release of master branch

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set env
        run: |
          echo "RELEASE_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "RELEASE_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          echo "RELEASE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build project
        run: |
          mvn versions:set -DnewVersion=${{ env.RELEASE_BRANCH }}-latest
          mvn clean install -DskipTests -DskipITs -Dmaven.test.skip=true --file pom.xml

      - name: Delete ${{ env.RELEASE_BRANCH }}-latest release
        uses: dev-drprasad/delete-tag-and-release@v0.1.3
        with:
          delete_release: true # default: false
          tag_name: ${{ env.RELEASE_BRANCH }}-latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release ${{ env.RELEASE_BRANCH }}-latest
          tag_name: ${{ env.RELEASE_BRANCH }}-latest
          body: Release ${{ env.RELEASE_BRANCH }}-latest
          draft: false
          prerelease: false
          files: liquibase-bigquery-${{ env.RELEASE_BRANCH }}-latest.jar