name: Run Functional Tests

on:
  workflow_call:
    inputs:
      latestMergeSha:
        description: 'Latest Merge sha of OSS PR'
        required: false
        default: ''
        type: string
      thisBranchName:
        description: 'Branch Name of OSS PR'
        required: false
        default: ''
        type: string

env:
  MAVEN_VERSION: '3.9.2'

jobs:
  functional-tests-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha || github.event.after}} # get the sha of the commit or the new commit created when branch is merged to master

      - name: Get Workflow Run URL
        id: get-workflow-url
        run: |
          repo_url="https://github.com/${{ github.repository }}"
          workflow_url="${repo_url}/actions/runs/${{ github.run_id }}"
          echo "workflow_url=${workflow_url}" >> $GITHUB_ENV


  run-pro-tests:
    needs: [setup]
    name: RUN Tests
    steps:
      - name: Dispatch an action and get the run ID
        uses: codex-/return-dispatch@v1
        id: return_dispatch
        with:
          token: ${{ secrets.LIQUIBOT_PAT }}
          repo: liquibase-pro-tests
          owner: liquibase
          workflow: test.yml
          workflow_inputs: {
            "liquibaseCommit": "${{ inputs.latestMergeSha }}",
            "runDescription": "${{ env.workflow_url }}",
            "liquibaseBranch": "${{ inputs.thisBranchName }}"
            }

      - name: Display run ID
        run: echo ${{ steps.return_dispatch.outputs.run_id }}

      - name: Report Details
        uses: actions/github-script@v6.4.1
        with:
          script: |
            const targetURL = "https://github.com/liquibase/liquibase-pro-tests/actions/runs/${{ steps.return_dispatch.outputs.run_id }}"
            core.notice("Pro-Tests Run URL: " + targetURL);

      #run the functional tests only against the head-branch of the PR
#      - name: Trigger Functional Tests Workflow
#        uses: peter-evans/repository-dispatch@v2
#        with:
#          token: ${{ secrets.RUN_FUNCTIONAL_TEST_HARNESS_TESTS_TOKEN }}
#          repository: liquibase/liquibase-pro-tests
#          event-type: run-functional-tests
#          client-payload: |
#            {
#              "liquibaseCommit": "${{ inputs.latestMergeSha }}",
#              "runDescription" : "${{ env.workflow_url }}",
#              "liquibaseBranch" : "${{ inputs.thisBranchName }}"
#            }